export const DEPARTMENTS = [
  {
    id: "cse",
    name: "Computer Science & Engineering",
    sections: [
      {
        id: "cse-a",
        name: "Section A",
        subjects: [
          { id: "os", name: "Operating Systems", code: "BTCT2305" },
          { id: "coa", name: "Computer Organization and Architecture", code: "BTCT2307" },
          { id: "uhv", name: "Universal Human Values", code: "BTCT2306" },
          { id: "dbms", name: "Database Management Systems", code: "BTCT2304" },
          { id: "dbms-lab", name: "Database Management Systems Lab", code: "BTCL2302" },
          { id: "eda-r", name: "Exploratory Data Analytics with R Lab", code: "BTCL2501" },
          { id: "se", name: "Software Engineering", code: "BTCT2501" },
          { id: "mfe", name: "Management for Engineers", code: "BTCT2901" },
          { id: "dssm", name: "Deterministic Stochastics and Statistical Methods", code: "BTCT2702" },
          { id: "aptitude", name: "Aptitude-2024", code: "APT24" },
          { id: "softskills", name: "Softskills-2024", code: "Skills 24" },
          { id: "mentoring", name: "Mentoring-2024", code: "Ment 24" },
          { id: "sports", name: "Sports-2024", code: "Sports 24" },
          { id: "photo-club", name: "Photography Club", code: "PCTAU01" },
        ],
      },
      {
        id: "cse-b",
        name: "Section B",
        subjects: [
          { id: "os", name: "Operating Systems", code: "BTCT2305" },
          { id: "coa", name: "Computer Organization and Architecture", code: "BTCT2307" },
          { id: "uhv", name: "Universal Human Values", code: "BTCT2306" },
          { id: "dbms", name: "Database Management Systems", code: "BTCT2304" },
          { id: "dbms-lab", name: "Database Management Systems Lab", code: "BTCL2302" },
          { id: "eda-r", name: "Exploratory Data Analytics with R Lab", code: "BTCL2501" },
          { id: "se", name: "Software Engineering", code: "BTCT2501" },
          { id: "mfe", name: "Management for Engineers", code: "BTCT2901" },
          { id: "dssm", name: "Deterministic Stochastics and Statistical Methods", code: "BTCT2702" },
          { id: "aptitude", name: "Aptitude-2024", code: "APT24" },
          { id: "softskills", name: "Softskills-2024", code: "Skills 24" },
          { id: "mentoring", name: "Mentoring-2024", code: "Ment 24" },
          { id: "sports", name: "Sports-2024", code: "Sports 24" },
          { id: "photo-club", name: "Photography Club", code: "PCTAU01" },
        ],
      },
    ],
  },
  {
    id: "aiml",
    name: "AI & Machine Learning",
    sections: [
      {
        id: "aiml-a",
        name: "Section A",
        subjects: [
          { id: "ml", name: "Machine Learning", code: "BTMT2501" },
          { id: "ml-lab", name: "Machine Learning Lab", code: "BTML2501" },
          { id: "uhv", name: "Universal Human Values", code: "BTMT2306" },
          { id: "mfe", name: "Management for Engineers", code: "BTMT2901" },
          { id: "ai", name: "Artificial Intelligence", code: "BTMT2502" },
          { id: "os", name: "Operating Systems", code: "BTMT2305" },
          { id: "coa", name: "Computer Organization and Architecture", code: "BTMT2307" },
          { id: "dbms", name: "Database Management Systems", code: "BTMT2304" },
          { id: "dbms-lab", name: "Database Management Systems Lab", code: "BTML2302" },
          { id: "library", name: "Library-2024", code: "Lib 24" },
          { id: "aptitude", name: "Aptitude-2024", code: "APT24" },
          { id: "mentoring", name: "Mentoring-2024", code: "Ment 24" },
          { id: "softskills", name: "Soft Skills", code: "SKILL24" },
          { id: "sports", name: "Sports-2024", code: "Sports 24" },
          { id: "media-club", name: "Media Club", code: "MCTAU13" },
        ],
      },
      {
        id: "aiml-b",
        name: "Section B",
        subjects: [
          { id: "ml", name: "Machine Learning", code: "BTMT2501" },
          { id: "ml-lab", name: "Machine Learning Lab", code: "BTML2501" },
          { id: "uhv", name: "Universal Human Values", code: "BTMT2306" },
          { id: "mfe", name: "Management for Engineers", code: "BTMT2901" },
          { id: "ai", name: "Artificial Intelligence", code: "BTMT2502" },
          { id: "os", name: "Operating Systems", code: "BTMT2305" },
          { id: "coa", name: "Computer Organization and Architecture", code: "BTMT2307" },
          { id: "dbms", name: "Database Management Systems", code: "BTMT2304" },
          { id: "dbms-lab", name: "Database Management Systems Lab", code: "BTML2302" },
          { id: "library", name: "Library-2024", code: "Lib 24" },
          { id: "aptitude", name: "Aptitude-2024", code: "APT24" },
          { id: "mentoring", name: "Mentoring-2024", code: "Ment 24" },
          { id: "softskills", name: "Soft Skills", code: "SKILL24" },
          { id: "sports", name: "Sports-2024", code: "Sports 24" },
          { id: "media-club", name: "Media Club", code: "MCTAU13" },
        ],
      },
    ],
  },
  {
    id: "aids",
    name: "AI & Data Science",
    sections: [
      {
        id: "aids-a",
        name: "Section A",
        subjects: [
          { id: "ds", name: "Data Science Foundations", code: "BTDS301" },
          { id: "ml", name: "Machine Learning", code: "BTDS302" },
          { id: "ai", name: "Artificial Intelligence", code: "BTDS303" },
          { id: "dbms", name: "Database Management Systems", code: "BTDS304" },
          { id: "uhv", name: "Universal Human Values", code: "BTDS305" },
        ],
      },
      {
        id: "aids-b",
        name: "Section B",
        subjects: [
          { id: "ds", name: "Data Science Foundations", code: "BTDS301" },
          { id: "ml", name: "Machine Learning", code: "BTDS302" },
          { id: "ai", name: "Artificial Intelligence", code: "BTDS303" },
          { id: "dbms", name: "Database Management Systems", code: "BTDS304" },
          { id: "uhv", name: "Universal Human Values", code: "BTDS305" },
        ],
      },
    ],
  },
];

export const TIME_PERIODS = [
  "09:00 AM - 10:00 AM",
  "10:00 AM - 11:00 AM",
  "11:15 AM - 12:15 PM",
  "12:15 PM - 01:15 PM",
  "02:00 PM - 03:00 PM",
  "03:00 PM - 04:00 PM",
];
